version: 2

sources:
  - name: ethereum
    tables:
      - name: transactions
  - name: tokens
    tables:
      - name: erc20
  - name: prices
    tables:
      - name: usd_with_native
  - name: uniswap_v3_ethereum
    tables:
      - name: Pair_evt_Swap
      - name: Factory_evt_PoolCreated

models:
  - name: univ3_base_trades
    description: "Base Uniswap V3 swaps on Ethereum with raw token amounts and addresses."
    columns:
      - name: block_date
        tests: [not_null]
      - name: block_number
        tests: [not_null]
      - name: evt_index
        tests: [not_null]

  - name: univ3_enrichments
    description: "Uniswap V3 swaps enriched with tx metadata and ERC20 token symbols and decimals."
    columns:
      - name: block_date
        tests: [not_null]
      - name: block_number
        tests: [not_null]
      - name: evt_index
        tests: [not_null]

  - name: univ3_prices
    description: "Uniswap V3 enriched swaps with USD pricing."
    columns:
      - name: block_date
        tests: [not_null]
      - name: block_number
        tests: [not_null]
      - name: evt_index
        tests: [not_null]


